all: neural-net_bgl makeTrainingSamples
	
neural-net_bgl: neural-net_bgl.cpp
	g++ neural-net_bgl.cpp -o neural-net_bgl -lboost_serialization

makeTrainingSamples: makeTrainingSamples.cpp
	g++ makeTrainingSamples.cpp -o makeTrainingSamples
